### ISSUE TITLE
Windows Problem with Docker Volume of Postgres

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [CodingGarden/inventory-app#2]
So on line 7 from the docker-compose file it says: - ./docker-data/db-data:/var/lib/postgresql/data  This works fine on my Mac but does not on Windows.  It complains about chmod (probably because docker is a different user?)  It is not something new perse (see docker-library/postgres#435) and there are many other issue's on git about it.
Being new myself to Docker i tried some stuff but i could not figure it out.  I hope you could tell me how to achieve the same on Windows so I could follow. ☺️

I have a windows 10 Home edition, I know you might say that it doesn’t work on windows 10 Home but it does indeed. You just have to get the Windows 10 Home Version 2004 and it will work! I have tried it and it works without volumes but when I map volumes it starts complaining about chmod thing! 💔

Hope you can help me, and I don’t have a Mac in hand to work on so my only choice is have it work on windows. 💔☺️

**Comment by w3cj** [comment]
Maybe something from this thread can help? https://github.com/docker/compose/issues/4303
Let me know if anything works! Also there's already another issue open here, so lets continue the conversation there: https://github.com/CodingGarden/inventory-app/issues/1

**Comment by YazeedAlKhalaf** [comment]
okay, I am sorry I just noticed it. My fault 😊
